### ISSUE TITLE
Epiloge 1/2 nesting

### ISSUE THREAD

**Issue by acabal** [standardebooks/leo-tolstoy_war-and-peace_louise-maude_aylmer-maude#1]
@vr8hub David Grigg brought this up while he was working on new print-toc code. The 1st and 2nd epilogues appear to be on a different nesting level in the generated ToC. Is this on purpose, or is there a nesting error?

**Comment by vr8hub** [comment]
It looks like there’s a text error and a nesting error.

The text error is that the epilogue-[12].xhtml files are both at level h2 and should be at h3. (The epilogue.xhtml is at h2 as it should be). But even after I fix that locally, the TOC still generates incorrectly. I’ve rechecked all of the epilogue* files, and I believe they’re all correct:
epilogue.xhtml is h2 (and division)
epilogue-X.xhtml are h3 (and part)
epilogue-X-Y.xhtml are h4 (and chapter)
I checked that the X-Y files all had both the previous sections, and labeled correctly. And the -X files have the division.

I also checked that content had the spine in the right order.
                <itemref idref="chapter-4-4-20.xhtml"/>
                <itemref idref="epilogue.xhtml"/>
                <itemref idref="epilogue-1.xhtml"/>
                <itemref idref="epilogue-1-1.xhtml"/>
                <itemref idref="epilogue-1-2.xhtml"/>
                <itemref idref="epilogue-1-3.xhtml"/>
                <itemref idref="epilogue-1-4.xhtml"/>
                <itemref idref="epilogue-1-5.xhtml"/>
                <itemref idref="epilogue-1-6.xhtml"/>
                <itemref idref="epilogue-1-7.xhtml"/>
                <itemref idref="epilogue-1-8.xhtml"/>
                <itemref idref="epilogue-1-9.xhtml"/>
                <itemref idref="epilogue-1-10.xhtml"/>
                <itemref idref="epilogue-1-11.xhtml"/>
                <itemref idref="epilogue-1-12.xhtml"/>
                <itemref idref="epilogue-1-13.xhtml"/>
                <itemref idref="epilogue-1-14.xhtml"/>
                <itemref idref="epilogue-1-15.xhtml"/>
                <itemref idref="epilogue-1-16.xhtml"/>
                <itemref idref="epilogue-2.xhtml"/>
                <itemref idref="epilogue-2-1.xhtml"/>

Here’s the outline of the pertinent portion of the newly generated TOC (after I fixed the h2 to h3 error in the -X files). The top-level epilogue.xhtml is correct, i.e. it’s at the same level as books 1-4. But then things go south. Epilogue-1 is at the same level as epilogue but should be subordinate to it. And epilogue-2 should also be one level below epilogue, at the same level as epilogue-1, but for some reason it jumps all the way out to the topmost level (above the halftitle, even).

		<li>
			<a href="text/book-4.xhtml">Book <span epub:type="z3998:roman">IV</span></a>
				<li>
					<a href="text/part-4-2.xhtml">Part <span epub:type="z3998:roman">II</span>: 1812</a>
				</li>
				<li>
					<a href="text/part-4-3.xhtml">Part <span epub:type="z3998:roman">III</span>: 1812</a>
				</li>
				<li>
					<a href="text/part-4-4.xhtml">Part <span epub:type="z3998:roman">IV</span>: 1812–13</a>
				</li>
			</ol>
		</li>
		<li>
			<a href="text/epilogue.xhtml">Epilogue</a>
		</li>
		<li>
			<a href="text/epilogue-1.xhtml">First Epilogue: 1813–20</a>
		</li>
	</ol>
</li>
<li>
	<a href="text/epilogue-2.xhtml">Second Epilogue</a>
</li>

It’s entirely possible I’m still missing something in the source, but if so I don’t know what it is.

Happy Thanksgiving if you’re in the States, and Happy Thanksgiving even if you’re not. :)

**Comment by vr8hub** [comment]
And ten seconds after I hit Send I saw it.

Two errors, both in the epilogue-[12].xhtml files. The first is the already mentioned h2 -> h3; the second is that they’re missing the division section. If I add both those in, then the ToC generates correctly.

**Comment by acabal** [comment]
OK great. Can you open a pull request whenever you have time? Happy Thanksgiving!
